config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
 
  namespace :admin do
      resources :users
      resources :posts
      resources :pages
      resources :services
      resources :notifications
      resources :announcements

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :pages
  resources :posts
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="text-center text-white mt-4" style="background-color: #473884;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register on Best Practices for free</span>
           <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-outline-light btn-rounded" %>
         
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      <span>© <%= Date.today.year %> Copyright</span>
      <a class="text-white" href="https://xhostcom.com/">Best Practices</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-dark bg-dark" style="background-color: #473884;">
  <div class="container mx-auto">
    <%= link_to "Best Practices", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "About", root_path, class: "nav-link" %></li>
         <li class="nav-item"><%= link_to "Products", root_path, class: "nav-link" %></li>
         <li class="nav-item"><%= link_to "Services", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Careers", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "News", root_path, class: "nav-link" %></li>
      </ul>
         <%= form_tag(posts_path, :method => "get",
                   class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          <%= text_field_tag :title, params[:title], placeholder: "Search Posts By Title", class: "form-control" %>
        </div>
        <% end %>

      <ul class="navbar-nav">
      <% if user_signed_in? %>
         <li class="nav-item"><%= link_to "Announcements", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="far fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:admin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item mx-2"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success nav-link" %></li>
          <li class="nav-item mx-2"><%= link_to "Login", new_user_session_path, class: "btn btn-primary nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<div class="container mx-auto">
  <% flash.each do |msg_type, message| %>
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>