config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
 
  namespace :admin do
      resources :users
      resources :posts
      resources :pages
      resources :services
      resources :notifications
      resources :announcements

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :pages
  resources :posts
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_field :body, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <% if page.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', page, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if page.persisted? %>
      <%= link_to "Cancel", page, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", pages_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Pages</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_page_path, class: 'btn btn-primary' do %>
    Add New Page
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Body</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <%= content_tag :tr, id: dom_id(page), class: dom_class(page) do %>
          

                      <td><%= page.title %></td>
                      <td><%= page.body %></td>
          
          
            <td><%= link_to 'Show', page %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<div class="page-header">
  <%= link_to pages_path, class: 'btn btn-default' do %>
    All Pages
  <% end %>
  <%= link_to edit_page_path(@page), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show page</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @page.title %></dd>
  <dt>Body:</dt>
  <dd><%= @page.body %></dd>
</dl>